- repo: local
  hooks: 
  - id: version-number
    name: Check consistency in version number
    entry: python ./.travis/precommit/fix_setup_version.py
    language: system
    pass_filenames: false

