- repo: local
  hooks:
  - id: version-number
    name: Check consistency in version number
    entry: python ./.travis/precommit/fix_setup_version.py
    language: system
    pass_filenames: false

  - id: yapf
    name: yapf
    entry: yapf
    language: system
    types: [python]
    args: ["-i"]

  # prospector: collection of linters
  - id: prospector
    language: system
    types: [file, python]
    exclude: .travis
    name: prospector
    description: "This hook runs Prospector: https://github.com/landscapeio/prospector"
    entry: prospector

# mypy: static type checking
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.770
  hooks:
  - id: mypy
    exclude: '^(doc/)|(examples/)|(playground/)'
